execute_process(
    COMMAND rustc --version
    OUTPUT_VARIABLE RUSTVER
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_VARIABLE RUSTERR
)
message(STATUS "RUSTVER='${RUSTVER}'")
message(STATUS "RUSTERR='${RUSTERR}'")
