Radix Relay: radix_relay::cli_utils Namespace Reference
radix_relay::cli_utils Namespace Reference
Classes
struct app_state
Runtime application state.
struct cli_args
Parsed command-line arguments.
class tui_sink
Custom spdlog sink that routes log messages to a display queue.
Typedefs
using tui_sink_mutex_t = tui_sink< std::mutex >
Type alias for mutex-protected TUI sink.
Functions
auto configure_logging (const cli_args &args, std::shared_ptr< async::async_queue< core::events::display_filter_input_t > > display_queue=nullptr) -> void
Configures spdlog logging based on CLI arguments.
auto print_app_banner (const app_state &state) -> void
Prints the application startup banner.
auto print_available_commands () -> void
Prints list of available interactive commands.
template<typename CommandHandler >
auto execute_cli_command (const cli_args &args, CommandHandler &command_handler) -> bool
Executes a command specified via CLI arguments.
auto setup_cli_app (CLI::App &app, cli_args &args) -> void
Configures CLI11 application with command-line options.
auto parse_cli_args (int argc, char **argv) -> cli_args
Parses command-line arguments into a cli_args structure.
auto validate_cli_args (const cli_args &args) -> bool
Validates parsed command-line arguments for logical consistency.
Typedef Documentation
tui_sink_mutex_t
using radix_relay::cli_utils::tui_sink_mutex_t = typedef tui_sink<std::mutex>
Type alias for mutex-protected TUI sink.
Definition at line 63 of file tui_sink.hpp.
Function Documentation
configure_logging()
auto radix_relay::cli_utils::configure_logging (const cli_args & args, std::shared_ptr< async::async_queue< core::events::display_filter_input_t > > display_queue = nullptr) -> void inline
Configures spdlog logging based on CLI arguments.
Parameters
args Parsed command-line arguments
display_queue Optional queue for routing log messages to TUI
Definition at line 31 of file app_init.hpp.
execute_cli_command()
template<typename CommandHandler > auto radix_relay::cli_utils::execute_cli_command (const cli_args & args, CommandHandler & command_handler) -> bool inline
Executes a command specified via CLI arguments.
Template Parameters
CommandHandler Callable type that handles typed commands
Parameters
args Parsed CLI arguments
command_handler Handler to invoke for commands
Returns
true if a command was executed, false otherwise
Definition at line 75 of file app_init.hpp.
References radix_relay::core::events::send::peer.
parse_cli_args()
auto radix_relay::cli_utils::parse_cli_args (int argc, char ** argv) -> cli_args inline
Parses command-line arguments into a cli_args structure.
Parameters
argc Argument count from main()
argv Argument vector from main()
Returns
Parsed command-line arguments
Definition at line 44 of file cli_parser.hpp.
References radix_relay::platform::expand_tilde_path(), radix_relay::cli_utils::cli_args::identity_path, and setup_cli_app().
print_app_banner()
auto radix_relay::cli_utils::print_app_banner (const app_state & state) -> void inline
Prints the application startup banner.
Parameters
state Current application state
Definition at line 48 of file app_init.hpp.
print_available_commands()
auto radix_relay::cli_utils::print_available_commands () -> void inline
Prints list of available interactive commands.
Definition at line 59 of file app_init.hpp.
setup_cli_app()
auto radix_relay::cli_utils::setup_cli_app (CLI::App & app, cli_args & args) -> void inline
Configures CLI11 application with command-line options.
Parameters
app CLI11 application instance
args Structure to populate with parsed arguments
Definition at line 63 of file cli_parser.hpp.
Referenced by parse_cli_args().
validate_cli_args()
auto radix_relay::cli_utils::validate_cli_args (const cli_args & args) -> bool inline
Validates parsed command-line arguments for logical consistency.
Parameters
args Parsed arguments to validate
Returns
true if arguments are valid, false otherwise
Definition at line 90 of file cli_parser.hpp.