Radix Relay: radix_relay::platform Namespace Reference
radix_relay::platform Namespace Reference
Functions
auto get_home_directory () -> std::string
Returns the user's home directory path.
auto get_temp_directory () -> std::string
Returns the system's temporary directory path.
auto expand_tilde_path (const std::string &path) -> std::string
Expands tilde (~) in path to home directory.
auto format_current_time_hms () -> std::string
Formats the current local time as HH:MM:SS.
auto current_timestamp_ms () -> std::uint64_t
Gets current timestamp in milliseconds since Unix epoch.
Function Documentation
current_timestamp_ms()
auto radix_relay::platform::current_timestamp_ms () -> std::uint64_t
Gets current timestamp in milliseconds since Unix epoch.
Returns
Current time as milliseconds since epoch (UTC)
Referenced by radix_relay::core::command_handler_context< Bridge >::emit(), radix_relay::core::presentation_handler::handle(), radix_relay::core::presentation_handler::handle(), radix_relay::core::presentation_handler::handle(), radix_relay::core::presentation_handler::handle(), radix_relay::core::make_command_handler(), and radix_relay::cli_utils::tui_sink< Mutex >::sink_it_().
expand_tilde_path()
auto radix_relay::platform::expand_tilde_path (const std::string & path) -> std::string
Expands tilde (~) in path to home directory.
Parameters
path Path possibly containing ~
Returns
Expanded absolute path
Referenced by radix_relay::cli_utils::parse_cli_args().
format_current_time_hms()
auto radix_relay::platform::format_current_time_hms () -> std::string
Formats the current local time as HH:MM:SS.
Returns
Current time formatted as "HH:MM:SS"
get_home_directory()
auto radix_relay::platform::get_home_directory () -> std::string
Returns the user's home directory path.
Returns
Home directory path
get_temp_directory()
auto radix_relay::platform::get_temp_directory () -> std::string
Returns the system's temporary directory path.
Returns
Temporary directory path