Radix Relay: radix_relay::core::interactive_cli Struct Reference
radix_relay::core::interactive_cli Struct Reference
Interactive command-line interface for user input.
#include <cli.hpp>
Public Member Functions
interactive_cli (std::string node_id, std::string mode, std::shared_ptr< async::async_queue< events::raw_command > > command_queue)
Constructs an interactive CLI.
auto run () -> void
Runs the interactive CLI loop (blocking).
auto handle_command (const std::string &input) -> bool
Handles a user command.
auto get_mode () const -> const std::string &
Returns the current transport mode.
Static Public Member Functions
static auto should_quit (const std::string &input) -> bool
Checks if the input is a quit command.
Detailed Description
Interactive command-line interface for user input.
Provides a blocking REPL that reads user commands from stdin and queues them for processing.
Definition at line 19 of file cli.hpp.
Constructor & Destructor Documentation
interactive_cli()
radix_relay::core::interactive_cli::interactive_cli (std::string node_id, std::string mode, std::shared_ptr< async::async_queue< events::raw_command > > command_queue) inline
Constructs an interactive CLI.
Parameters
node_id Node identifier for display
mode Initial transport mode
command_queue Queue for outgoing raw commands
Definition at line 28 of file cli.hpp.
Member Function Documentation
get_mode()
auto radix_relay::core::interactive_cli::get_mode () const -> const std::string & inline
Returns the current transport mode.
Returns
Current mode string
Definition at line 103 of file cli.hpp.
handle_command()
auto radix_relay::core::interactive_cli::handle_command (const std::string & input) -> bool inline
Handles a user command.
Parameters
input User input string
Returns
true if command was handled, false otherwise
Definition at line 80 of file cli.hpp.
References radix_relay::core::events::raw_command::input.
Referenced by run().
run()
auto radix_relay::core::interactive_cli::run () -> void inline
Runs the interactive CLI loop (blocking).
Reads lines from stdin and processes commands until user quits or EOF.
Definition at line 39 of file cli.hpp.
References handle_command(), and should_quit().
should_quit()
static auto radix_relay::core::interactive_cli::should_quit (const std::string & input) -> bool inline static
Checks if the input is a quit command.
Parameters
input User input string
Returns
true if user wants to quit, false otherwise
Definition at line 65 of file cli.hpp.
Referenced by run().
The documentation for this struct was generated from the following file:
lib/core/include/core/cli.hpp