[workspace]
resolver = "2"

members = [
    "signal_bridge",
]

[workspace.dependencies]
# Unified versions to align with libsignal dependencies (libsignal uses rand 0.9.2)
rand = "0.9.2"
rand_core = "0.9"
getrandom = "0.3"
